name: Hello GitHub Actions
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      COURSE: Cloud Computing 
    steps:
      - run: echo "Hello from ${COURSE}!"
      - name: Hello Github Action
        run: echo "Hello from GitHub Actions!"  
      - run: echo "I'll list files."
      - run: ls -al
